Update Q7 for GHAS
FidelusAleksander/githubcertified pull request #128
Opened 2024-01-06 21:46 UTC by garysassano

## PR Type

- [x] Content changes (add/update questions, answers, explanations)
- [ ] Bugfix
- [ ] Feature
- [ ] Refactor (no functional changes)
- [ ] Documentation changes
- [ ] Other

## What's new?
Current question has two possible correct answers and not too much clear.

## Related issue(s)

## Screenshots

2024-01-07 19:38 UTC, FidelusAleksander reviewed
Hi @garysassano 

1.  I'm not sure which other answer You think is correct aswell in the current question? I personally think the current state is correct, but curious to hear Your view.
2. This is a whole question rewrite, instead add a new question with what You just wrote please.

2024-01-08 00:17 UTC, garysassano commented
This option is also correct: `Secret scanning scans your code for potential vulnerabilities that could expose secrets such as private keys or tokens.`

It's a bit generic since it says `code` instead of `Git history on all branches` but still correct overall.

2024-01-08 00:18 UTC, garysassano commented
This option is also correct: `Secret scanning scans your code for potential vulnerabilities that could expose secrets such as private keys or tokens.`

It's a bit generic since it says `code` instead of `Git history on all branches`, yet still correct overall.

2024-01-08 04:51 UTC, garysassano commented
@FidelusAleksander Let's make the answer options less ambiguous.

2024-01-08 08:36 UTC, FidelusAleksander requested changes
Small but important change, then it's ready to merge

2024-01-08 08:36 UTC, FidelusAleksander commented on content/questions/advanced_security/question-007.md
> +4. [ ] Secret scanning is a git hook that will scan your commits for secrets such as private keys or tokens before they are pushed to GitHub.
```suggestion
1. [ ] Secret scanning scans your repository for potential code vulnerabilities that could expose secrets such as private keys or tokens.
1. [ ] Secret scanning is a tool for secure secret storage and management.
1. [ ] Secret scanning is a git hook that will scan your commits for secrets such as private keys or tokens before they are pushed to GitHub.
```

2024-01-08 08:59 UTC, FidelusAleksander commented
@garysassano 

https://github.com/FidelusAleksander/githubcertified/pull/128/commits/de9770f257133e4c6f795ee15f53cad3c6f0899f

This commit was good, but You changed it again into a multiple choice question syntax :)

2024-01-08 09:04 UTC, garysassano commented
@FidelusAleksander My bad, didn't realize that's how the current system works: I thought the two syntaxes were interchangeable.

2024-01-08 09:09 UTC, FidelusAleksander approved these changes

2024-01-08 09:09 UTC, merged